import type { Country, DailyCountryStat, Report } from "@/lib/types";

const now = "2026-05-08T09:00:00.000Z";

export const demoCountries: Country[] = [
  { id: "arg", name: "Argentina", iso2: "AR", iso3: "ARG", slug: "argentina", lat: -38.4161, lng: -63.6167 },
  { id: "chl", name: "Chile", iso2: "CL", iso3: "CHL", slug: "chile", lat: -35.6751, lng: -71.543 },
  { id: "che", name: "Switzerland", iso2: "CH", iso3: "CHE", slug: "switzerland", lat: 46.8182, lng: 8.2275 },
  { id: "isr", name: "Israel", iso2: "IL", iso3: "ISR", slug: "israel", lat: 31.0461, lng: 34.8516 },
  { id: "nld", name: "Netherlands", iso2: "NL", iso3: "NLD", slug: "netherlands", lat: 52.1326, lng: 5.2913 },
  { id: "fra", name: "France", iso2: "FR", iso3: "FRA", slug: "france", lat: 46.2276, lng: 2.2137 },
  { id: "zaf", name: "South Africa", iso2: "ZA", iso3: "ZAF", slug: "south-africa", lat: -30.5595, lng: 22.9375 },
  { id: "cpv", name: "Cabo Verde", iso2: "CV", iso3: "CPV", slug: "cabo-verde", lat: 16.5388, lng: -23.0418 },
  { id: "esp", name: "Spain", iso2: "ES", iso3: "ESP", slug: "spain", lat: 40.4637, lng: -3.7492 },
  { id: "deu", name: "Germany", iso2: "DE", iso3: "DEU", slug: "germany", lat: 51.1657, lng: 10.4515 },
  { id: "dnk", name: "Denmark", iso2: "DK", iso3: "DNK", slug: "denmark", lat: 56.2639, lng: 9.5018 },
  { id: "can", name: "Canada", iso2: "CA", iso3: "CAN", slug: "canada", lat: 56.1304, lng: -106.3468 },
  { id: "tur", name: "Turkey", iso2: "TR", iso3: "TUR", slug: "turkey", lat: 38.9637, lng: 35.2433 },
  { id: "nzl", name: "New Zealand", iso2: "NZ", iso3: "NZL", slug: "new-zealand", lat: -40.9006, lng: 174.886 },
  { id: "swe", name: "Sweden", iso2: "SE", iso3: "SWE", slug: "sweden", lat: 60.1282, lng: 18.6435 },
  { id: "gbr", name: "United Kingdom", iso2: "GB", iso3: "GBR", slug: "united-kingdom", lat: 55.3781, lng: -3.436 },
  { id: "usa", name: "United States", iso2: "US", iso3: "USA", slug: "united-states", lat: 37.0902, lng: -95.7129 },
  { id: "sgp", name: "Singapore", iso2: "SG", iso3: "SGP", slug: "singapore", lat: 1.3521, lng: 103.8198 },
  { id: "kna", name: "Saint Kitts and Nevis", iso2: "KN", iso3: "KNA", slug: "saint-kitts-and-nevis", lat: 17.3578, lng: -62.783 }
];

export const demoReports: Report[] = [
  {
    id: "seed-arg-1",
    country_id: "arg",
    country: demoCountries[0],
    location_name: "Patagonia",
    lat: -41.1335,
    lng: -71.31,
    status: "confirmed",
    case_count: 8,
    death_count: 1,
    suspected_count: 0,
    report_date: "2026-04-22T12:00:00.000Z",
    source_name: "Seed data",
    source_url: "https://example.com/seed-data#argentina",
    source_type: "manual",
    confidence: "low",
    summary: "Demo seed report for UI validation. Replace with verified public source before production use.",
    raw_title: "Seed data: Argentina hantavirus report",
    raw_text: null,
    created_at: now,
    updated_at: now
  },
  {
    id: "seed-chl-1",
    country_id: "chl",
    country: demoCountries[1],
    location_name: "Los Lagos",
    lat: -41.47,
    lng: -72.94,
    status: "suspected",
    case_count: 0,
    death_count: 0,
    suspected_count: 6,
    report_date: "2026-04-29T08:30:00.000Z",
    source_name: "Seed data",
    source_url: "https://example.com/seed-data#chile",
    source_type: "manual",
    confidence: "low",
    summary: "Demo suspected cluster used to exercise suspected-only counting.",
    raw_title: "Seed data: Chile suspected reports",
    raw_text: null,
    created_at: now,
    updated_at: now
  },
  {
    id: "seed-che-1",
    country_id: "che",
    country: demoCountries[2],
    location_name: "Zurich",
    lat: 47.3769,
    lng: 8.5417,
    status: "confirmed",
    case_count: 1,
    death_count: 0,
    suspected_count: 0,
    report_date: "2026-05-06T12:00:00.000Z",
    source_name: "Swiss Federal Office of Public Health",
    source_url: "https://www.blw.admin.ch/en/newnsb/p--A7yPSfxdBqR0N9kZMC",
    source_type: "official",
    confidence: "high",
    summary: "Swiss authorities reported one positive hantavirus test in a man treated at University Hospital Zurich after MV Hondius travel.",
    raw_title: "Patient with a hantavirus infection being treated in hospital",
    raw_text: null,
    created_at: now,
    updated_at: now
  },
  {
    id: "seed-isr-1",
    country_id: "isr",
    country: demoCountries[3],
    location_name: "Israel",
    lat: 31.0461,
    lng: 34.8516,
    status: "confirmed",
    case_count: 1,
    death_count: 0,
    suspected_count: 0,
    report_date: "2026-05-07T12:53:00.000Z",
    source_name: "The Jerusalem Post",
    source_url: "https://www.jpost.com/israel-news/article-895478",
    source_type: "news",
    confidence: "medium",
    summary: "Israeli media reported a first diagnosed hantavirus case in Israel, said to have been reported to the Health Ministry after travel in Eastern Europe.",
    raw_title: "First case of hantavirus diagnosed in Israel, reported to Health Ministry after visit to Europe",
    raw_text: null,
    created_at: now,
    updated_at: now
  },
  {
    id: "seed-nld-1",
    country_id: "nld",
    country: demoCountries[4],
    location_name: "Netherlands-linked MV Hondius case",
    lat: 52.1326,
    lng: 5.2913,
    status: "confirmed",
    case_count: 5,
    death_count: 0,
    suspected_count: 0,
    report_date: "2026-05-05T07:08:00.000Z",
    source_name: "NL Times",
    source_url: "https://nltimes.nl/2026/05/05/now-7-hantavirus-infections-dutch-cruise-ship-incl-3-dead",
    source_type: "news",
    confidence: "medium",
    summary: "Netherlands-linked reporting tracks the MV Hondius cluster. Later WHO/UN updates reported five laboratory-confirmed infections and three suspected cases across the event.",
    raw_title: "WHO: Now 7 hantavirus infections on Dutch cruise ship, incl. 3 dead",
    raw_text: null,
    created_at: now,
    updated_at: now
  },
  {
    id: "seed-nld-death-1",
    country_id: "nld",
    country: demoCountries[4],
    location_name: "MV Hondius outbreak fatalities",
    lat: 52.1326,
    lng: 5.2913,
    status: "death",
    case_count: 0,
    death_count: 3,
    suspected_count: 0,
    report_date: "2026-05-05T07:10:00.000Z",
    source_name: "NL Times",
    source_url: "https://nltimes.nl/2026/05/05/now-7-hantavirus-infections-dutch-cruise-ship-incl-3-dead#fatalities",
    source_type: "news",
    confidence: "medium",
    summary: "Cluster reporting includes 3 deaths linked to hantavirus infections associated with MV Hondius travel.",
    raw_title: "WHO: Now 7 hantavirus infections on Dutch cruise ship, incl. 3 dead",
    raw_text: null,
    created_at: now,
    updated_at: now
  },
  {
    id: "seed-who-2026-05-07-1",
    country_id: "nld",
    country: demoCountries[4],
    location_name: "MV Hondius multi-country cluster",
    lat: 52.1326,
    lng: 5.2913,
    status: "official_update",
    case_count: 5,
    death_count: 3,
    suspected_count: 3,
    report_date: "2026-05-07T16:00:00.000Z",
    source_name: "World Health Organization",
    source_url: "https://www.who.int/news/item/07-05-2026-who-s-response-to-hantavirus-cases-linked-to-a-cruise-ship",
    source_type: "official",
    confidence: "high",
    summary: "WHO said eight cases had been reported so far in the MV Hondius cluster, including three deaths, with five of the eight confirmed as hantavirus. WHO assessed the public health risk as low while noting more cases may be reported during the incubation period.",
    raw_title: "WHO's response to hantavirus cases linked to a cruise ship",
    raw_text: null,
    created_at: now,
    updated_at: now
  },
  {
    id: "seed-ecdc-2026-05-07-1",
    country_id: "nld",
    country: demoCountries[4],
    location_name: "EU/EEA response to MV Hondius cluster",
    lat: 52.1326,
    lng: 5.2913,
    status: "official_update",
    case_count: 0,
    death_count: 0,
    suspected_count: 0,
    report_date: "2026-05-07T17:30:00.000Z",
    source_name: "ECDC",
    source_url: "https://www.ecdc.europa.eu/en/infectious-disease-topics/hantavirus-infection/surveillance-and-updates/andes-hantavirus-outbreak",
    source_type: "official",
    confidence: "high",
    summary: "ECDC's outbreak page says it was notified on 2 May, describes an Andes hantavirus cluster on a Dutch-flagged ship with passengers and crew from 23 countries, and assesses the risk to the EU/EEA general population as very low.",
    raw_title: "Andes Hantavirus outbreak in cruise ship, May 2026",
    raw_text: null,
    created_at: now,
    updated_at: now
  },
  {
    id: "seed-singapore-cda-2026-05-07-1",
    country_id: "sgp",
    country: demoCountries[17],
    location_name: "Singapore residents under testing",
    lat: 1.3521,
    lng: 103.8198,
    status: "monitoring",
    case_count: 0,
    death_count: 0,
    suspected_count: 0,
    report_date: "2026-05-07T14:40:00.000Z",
    source_name: "Singapore Communicable Diseases Agency",
    source_url: "https://www.cda.gov.sg/news-and-events/public-health-measures-activated-for-two-singapore-residents-onboard-mv-hondius/",
    source_type: "official",
    confidence: "high",
    summary: "Singapore CDA said two residents who had been onboard MV Hondius were isolated at NCID and tested for hantavirus. One had a runny nose and the other was asymptomatic; results were pending and public risk was assessed as low.",
    raw_title: "Public health measures activated for two Singapore residents onboard MV Hondius",
    raw_text: null,
    created_at: now,
    updated_at: now
  },
  {
    id: "seed-guardian-2026-05-07-1",
    country_id: "gbr",
    country: demoCountries[15],
    location_name: "Disembarked passenger tracing",
    lat: 55.3781,
    lng: -3.436,
    status: "monitoring",
    case_count: 0,
    death_count: 0,
    suspected_count: 0,
    report_date: "2026-05-07T15:30:00.000Z",
    source_name: "The Guardian",
    source_url: "https://www.theguardian.com/world/2026/may/07/global-race-under-way-to-trace-passengers-who-left-hantavirus-ship-before-outbreak-confirmed",
    source_type: "news",
    confidence: "medium",
    summary: "Authorities were tracing passengers who disembarked before the outbreak was confirmed. Countries named in reporting included the US, UK, Australia, Singapore, and Switzerland; no secondary infections were confirmed in the report.",
    raw_title: "Global race under way to trace passengers who left hantavirus ship before outbreak confirmed",
    raw_text: null,
    created_at: now,
    updated_at: now
  },
  {
    id: "seed-reuters-2026-05-07-1",
    country_id: "gbr",
    country: demoCountries[15],
    location_name: "Passengers traced after St Helena disembarkation",
    lat: 55.3781,
    lng: -3.436,
    status: "monitoring",
    case_count: 0,
    death_count: 0,
    suspected_count: 0,
    report_date: "2026-05-07T13:33:00.000Z",
    source_name: "Reuters via The Star",
    source_url: "https://www.thestar.com.my/news/world/2026/05/07/countries-scramble-to-track-passengers-of-virus-hit-cruise-ship",
    source_type: "news",
    confidence: "medium",
    summary: "Reuters reported that countries were tracing people who disembarked at St Helena before the outbreak was detected, including travelers from at least 12 countries; the operator said those passengers had been contacted.",
    raw_title: "Countries scramble to track passengers of virus-hit cruise ship",
    raw_text: null,
    created_at: now,
    updated_at: now
  },
  {
    id: "seed-businessinsider-2026-05-08-1",
    country_id: "usa",
    country: demoCountries[16],
    location_name: "Global explainer and US monitoring context",
    lat: 37.0902,
    lng: -95.7129,
    status: "official_update",
    case_count: 0,
    death_count: 0,
    suspected_count: 0,
    report_date: "2026-05-08T08:30:00.000Z",
    source_name: "Business Insider",
    source_url: "https://www.businessinsider.com/cruise-ship-atlantic-viral-outbreak-deaths-hantavirus-world-health-organization-2026-5",
    source_type: "news",
    confidence: "medium",
    summary: "Business Insider summarized the latest WHO-linked figures: eight reported cases, three deaths, low public risk, and ongoing investigation into the Andes hantavirus cluster connected to MV Hondius travel.",
    raw_title: "What is hantavirus? What to know after 3 deaths tied to a cruise ship outbreak",
    raw_text: null,
    created_at: now,
    updated_at: now
  },
  {
    id: "seed-lemonde-2026-05-08-1",
    country_id: "fra",
    country: demoCountries[5],
    location_name: "France media explainer",
    lat: 46.2276,
    lng: 2.2137,
    status: "official_update",
    case_count: 0,
    death_count: 0,
    suspected_count: 0,
    report_date: "2026-05-08T08:00:00.000Z",
    source_name: "Le Monde",
    source_url: "https://www.lemonde.fr/en/les-decodeurs/article/2026/05/08/from-the-andes-strain-to-the-fatality-rate-a-glossary-of-terms-for-understanding-hantaviruses_6753238_8.html",
    source_type: "news",
    confidence: "medium",
    summary: "Le Monde published a glossary explaining the Andes strain, transmission, incubation period, fatality rate, and why WHO views the broader public health risk as low despite the seriousness of the MV Hondius cluster.",
    raw_title: "From the Andes strain to the fatality rate, a glossary of terms for understanding hantaviruses",
    raw_text: null,
    created_at: now,
    updated_at: now
  },
  {
    id: "seed-toi-2026-05-08-1",
    country_id: "nld",
    country: demoCountries[4],
    location_name: "MV Hondius follow-up coverage",
    lat: 52.1326,
    lng: 5.2913,
    status: "monitoring",
    case_count: 0,
    death_count: 0,
    suspected_count: 0,
    report_date: "2026-05-08T07:45:00.000Z",
    source_name: "Times of India",
    source_url: "https://timesofindia.indiatimes.com/etimes/wellness/hantavirus-outbreak-on-mv-hondius-health-officials-track-dozens-who-left-ship-after-first-fatality-whats-next/articleshow/130936945.cms",
    source_type: "news",
    confidence: "medium",
    summary: "Times of India reported continued international tracking of travelers connected to MV Hondius and described why the Andes strain is receiving attention while broader public risk remains low.",
    raw_title: "Hantavirus outbreak on MV Hondius: Health officials track dozens who left ship after first fatality; what's next?",
    raw_text: null,
    created_at: now,
    updated_at: now
  },
  {
    id: "seed-fra-1",
    country_id: "fra",
    country: demoCountries[5],
    location_name: "France",
    lat: 46.2276,
    lng: 2.2137,
    status: "monitoring",
    case_count: 0,
    death_count: 0,
    suspected_count: 0,
    report_date: "2026-05-07T13:00:00.000Z",
    source_name: "Manual tracker entry",
    source_url: "https://example.com/seed-data#france",
    source_type: "manual",
    confidence: "low",
    summary: "Manual monitoring marker for France. It does not affect confirmed totals until a source-linked confirmed report is added.",
    raw_title: "Manual tracker entry: France monitoring highlight",
    raw_text: null,
    created_at: now,
    updated_at: now
  },
  {
    id: "seed-zaf-1",
    country_id: "zaf",
    country: demoCountries[6],
    location_name: "Western Cape",
    lat: -33.9,
    lng: 18.42,
    status: "official_update",
    case_count: 0,
    death_count: 0,
    suspected_count: 2,
    report_date: "2026-05-03T11:30:00.000Z",
    source_name: "Seed data",
    source_url: "https://example.com/seed-data#south-africa",
    source_type: "manual",
    confidence: "low",
    summary: "Demo official-update style record; source URL is placeholder seed data.",
    raw_title: "Seed data: South Africa update",
    raw_text: null,
    created_at: now,
    updated_at: now
  },
  {
    id: "seed-cpv-1",
    country_id: "cpv",
    country: demoCountries[7],
    location_name: "Praia",
    lat: 14.933,
    lng: -23.513,
    status: "suspected",
    case_count: 0,
    death_count: 0,
    suspected_count: 3,
    report_date: "2026-05-04T10:15:00.000Z",
    source_name: "Seed data",
    source_url: "https://example.com/seed-data#cabo-verde",
    source_type: "manual",
    confidence: "low",
    summary: "Demo suspected entry for map coverage testing.",
    raw_title: "Seed data: Cabo Verde suspected reports",
    raw_text: null,
    created_at: now,
    updated_at: now
  },
  {
    id: "seed-esp-1",
    country_id: "esp",
    country: demoCountries[8],
    location_name: "Canary Islands",
    lat: 28.2916,
    lng: -16.6291,
    status: "monitoring",
    case_count: 0,
    death_count: 0,
    suspected_count: 0,
    report_date: "2026-05-05T14:00:00.000Z",
    source_name: "Seed data",
    source_url: "https://example.com/seed-data#canary-islands",
    source_type: "manual",
    confidence: "low",
    summary: "Demo monitoring record linked to travel-report UI testing.",
    raw_title: "Seed data: Canary Islands monitoring",
    raw_text: null,
    created_at: now,
    updated_at: now
  },
  {
    id: "watch-deu-1",
    country_id: "deu",
    country: demoCountries[9],
    location_name: "Germany",
    lat: 51.1657,
    lng: 10.4515,
    status: "monitoring",
    case_count: 0,
    death_count: 0,
    suspected_count: 0,
    report_date: "2026-05-07T15:00:00.000Z",
    source_name: "Manual monitoring list",
    source_url: "https://example.com/monitoring#germany",
    source_type: "manual",
    confidence: "low",
    summary: "Monitoring watch country. Possible hantavirus-related reports require verification before being counted.",
    raw_title: "Monitoring watch: Germany",
    raw_text: null,
    created_at: now,
    updated_at: now
  },
  {
    id: "watch-dnk-1",
    country_id: "dnk",
    country: demoCountries[10],
    location_name: "Denmark",
    lat: 56.2639,
    lng: 9.5018,
    status: "monitoring",
    case_count: 0,
    death_count: 0,
    suspected_count: 0,
    report_date: "2026-05-07T15:01:00.000Z",
    source_name: "Manual monitoring list",
    source_url: "https://example.com/monitoring#denmark",
    source_type: "manual",
    confidence: "low",
    summary: "Monitoring watch country. Possible hantavirus-related reports require verification before being counted.",
    raw_title: "Monitoring watch: Denmark",
    raw_text: null,
    created_at: now,
    updated_at: now
  },
  {
    id: "watch-can-1",
    country_id: "can",
    country: demoCountries[11],
    location_name: "Canada",
    lat: 56.1304,
    lng: -106.3468,
    status: "monitoring",
    case_count: 0,
    death_count: 0,
    suspected_count: 0,
    report_date: "2026-05-07T15:02:00.000Z",
    source_name: "Manual monitoring list",
    source_url: "https://example.com/monitoring#canada",
    source_type: "manual",
    confidence: "low",
    summary: "Monitoring watch country. Possible hantavirus-related reports require verification before being counted.",
    raw_title: "Monitoring watch: Canada",
    raw_text: null,
    created_at: now,
    updated_at: now
  },
  {
    id: "watch-tur-1",
    country_id: "tur",
    country: demoCountries[12],
    location_name: "Turkey",
    lat: 38.9637,
    lng: 35.2433,
    status: "monitoring",
    case_count: 0,
    death_count: 0,
    suspected_count: 0,
    report_date: "2026-05-07T15:03:00.000Z",
    source_name: "Manual monitoring list",
    source_url: "https://example.com/monitoring#turkey",
    source_type: "manual",
    confidence: "low",
    summary: "Monitoring watch country. Possible hantavirus-related reports require verification before being counted.",
    raw_title: "Monitoring watch: Turkey",
    raw_text: null,
    created_at: now,
    updated_at: now
  },
  {
    id: "watch-nzl-1",
    country_id: "nzl",
    country: demoCountries[13],
    location_name: "New Zealand",
    lat: -40.9006,
    lng: 174.886,
    status: "monitoring",
    case_count: 0,
    death_count: 0,
    suspected_count: 0,
    report_date: "2026-05-07T15:04:00.000Z",
    source_name: "Manual monitoring list",
    source_url: "https://example.com/monitoring#new-zealand",
    source_type: "manual",
    confidence: "low",
    summary: "Monitoring watch country. Possible hantavirus-related reports require verification before being counted.",
    raw_title: "Monitoring watch: New Zealand",
    raw_text: null,
    created_at: now,
    updated_at: now
  },
  {
    id: "watch-swe-1",
    country_id: "swe",
    country: demoCountries[14],
    location_name: "Sweden",
    lat: 60.1282,
    lng: 18.6435,
    status: "monitoring",
    case_count: 0,
    death_count: 0,
    suspected_count: 0,
    report_date: "2026-05-07T15:05:00.000Z",
    source_name: "Manual monitoring list",
    source_url: "https://example.com/monitoring#sweden",
    source_type: "manual",
    confidence: "low",
    summary: "Monitoring watch country. Possible hantavirus-related reports require verification before being counted.",
    raw_title: "Monitoring watch: Sweden",
    raw_text: null,
    created_at: now,
    updated_at: now
  },
  {
    id: "watch-gbr-1",
    country_id: "gbr",
    country: demoCountries[15],
    location_name: "United Kingdom",
    lat: 55.3781,
    lng: -3.436,
    status: "monitoring",
    case_count: 0,
    death_count: 0,
    suspected_count: 0,
    report_date: "2026-05-07T15:06:00.000Z",
    source_name: "Manual monitoring list",
    source_url: "https://example.com/monitoring#united-kingdom",
    source_type: "manual",
    confidence: "low",
    summary: "Monitoring watch country. Possible hantavirus-related reports require verification before being counted.",
    raw_title: "Monitoring watch: United Kingdom",
    raw_text: null,
    created_at: now,
    updated_at: now
  },
  {
    id: "watch-usa-1",
    country_id: "usa",
    country: demoCountries[16],
    location_name: "United States",
    lat: 37.0902,
    lng: -95.7129,
    status: "monitoring",
    case_count: 0,
    death_count: 0,
    suspected_count: 0,
    report_date: "2026-05-07T15:07:00.000Z",
    source_name: "Manual monitoring list",
    source_url: "https://example.com/monitoring#united-states",
    source_type: "manual",
    confidence: "low",
    summary: "Monitoring watch country. Possible hantavirus-related reports require verification before being counted.",
    raw_title: "Monitoring watch: United States",
    raw_text: null,
    created_at: now,
    updated_at: now
  },
  {
    id: "watch-sgp-1",
    country_id: "sgp",
    country: demoCountries[17],
    location_name: "Singapore",
    lat: 1.3521,
    lng: 103.8198,
    status: "monitoring",
    case_count: 0,
    death_count: 0,
    suspected_count: 0,
    report_date: "2026-05-07T15:08:00.000Z",
    source_name: "Manual monitoring list",
    source_url: "https://example.com/monitoring#singapore",
    source_type: "manual",
    confidence: "low",
    summary: "Monitoring watch country. Possible hantavirus-related reports require verification before being counted.",
    raw_title: "Monitoring watch: Singapore",
    raw_text: null,
    created_at: now,
    updated_at: now
  },
  {
    id: "watch-kna-1",
    country_id: "kna",
    country: demoCountries[18],
    location_name: "Saint Kitts and Nevis",
    lat: 17.3578,
    lng: -62.783,
    status: "monitoring",
    case_count: 0,
    death_count: 0,
    suspected_count: 0,
    report_date: "2026-05-07T15:09:00.000Z",
    source_name: "Manual monitoring list",
    source_url: "https://example.com/monitoring#saint-kitts-and-nevis",
    source_type: "manual",
    confidence: "low",
    summary: "Monitoring watch country. Possible hantavirus-related reports require verification before being counted.",
    raw_title: "Monitoring watch: Saint Kitts and Nevis",
    raw_text: null,
    created_at: now,
    updated_at: now
  }
];

export const demoDailyStats: DailyCountryStat[] = demoCountries.flatMap((country) => {
  const reports = demoReports.filter((report) => report.country_id === country.id);
  let confirmed = 0;
  let suspected = 0;
  let deaths = 0;
  return reports.map((report) => {
    const countsForTotals = report.source_type !== "social" && report.confidence !== "low";
    const newConfirmed = countsForTotals && report.status === "confirmed" ? report.case_count : 0;
    const newSuspected = countsForTotals && report.status === "suspected" ? report.suspected_count : 0;
    const newDeaths = countsForTotals && report.status === "death" ? report.death_count : 0;
    confirmed += newConfirmed;
    suspected += newSuspected;
    deaths += newDeaths;
    return {
      id: `stat-${report.id}`,
      country_id: country.id,
      country,
      date: report.report_date.slice(0, 10),
      confirmed_total: confirmed,
      suspected_total: suspected,
      deaths_total: deaths,
      new_confirmed: newConfirmed,
      new_suspected: newSuspected,
      new_deaths: newDeaths,
      created_at: now
    };
  });
});
